<h1>Header</h1>

<p>
    <a>Create New</a>
</p>

<div>

    <div class="drop_shadow postit green">

        <a class="deleteLink">x</a>

        <div class="sexy_date">
            <h1 class="day">dd</h1>
            <h1 class="month">MMM</h1>
            <h1 class="year">yyyy</h1>
        </div>

        <h2>Title</h2>
        <p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.</p>

        <a>Details</a>

    </div>
</div>

<?php

#require "_index.phtml";
#require "_edit.phtml";
#require "_page404.phtml";

$js = "
require(['jquery', 'jquery.plugins'], function($) {
    $.refreshPage();
});";

$this->placeholder('scripts')->set($js);